
CompactRaidDB = {
	["showSolo"] = 1,
	["showtooltip"] = 1,
	["healthColor"] = "0.0,1.0,0.0",
	["clickDownMode"] = 1,
	["showParty"] = 1,
	["modules"] = {
		["Artwork"] = {
			["font"] = "Fonts\\blei00d.TTF",
			["background"] = "Interface\\DialogFrame\\UI-DialogBox-Background",
			["border"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["statusbar"] = "Interface\\BUTTONS\\WHITE8X8.BLP",
		},
		["RaidDebuff"] = {
			["selTier"] = 6,
			["customDebuffs"] = {
			},
			["yoffset"] = 0,
			["scale"] = 100,
			["xoffset"] = 0,
			["selBoss"] = 1161,
			["selInstance"] = 457,
			["userLevels"] = {
			},
		},
	},
	["lock"] = 1,
	["powerColor"] = "0.0,0.0,1.0",
	["groupSwapNoNotify"] = 1,
	["showToolboxes"] = 1,
	["powerBarHeight"] = 1,
	["showRoleIcon"] = 1,
	["showDebuffs"] = 1,
	["nameWidthLimit"] = 75,
	["showDispels"] = 1,
	["version"] = 4.02,
	["showbarbkgnd"] = 1,
	["height"] = 36,
	["showPrivIcons"] = 1,
	["nameYOffset"] = 0,
	["tooltipPosition"] = 1,
	["scale"] = 100,
	["showBuffs"] = 1,
	["spacing"] = 1,
	["hideToolboxes"] = false,
	["showRaidIcon"] = 1,
	["containerBorderSize"] = 12,
	["containerAlpha"] = 75,
	["nameHeight"] = 12,
	["grouphoriz"] = false,
	["raidFilter"] = "CLASS",
	["width"] = 64,
	["keepgroupstogether"] = 1,
	["showDirectionArrow"] = 1,
	["healthtextmode"] = 0,
	["unitBkColor"] = "0.0,0.0,0.0",
	["nameXOffset"] = 0,
	["onlyDispellable"] = false,
	["nameColor"] = "1.0,1.0,1.0",
	["outrangeAlpha"] = 40,
}
