
SavedInstancesDB = {
	["DBVersion"] = 12,
	["Toons"] = {
		["更多的治療 - 冰風崗哨"] = {
			["lastbossyell"] = "格利伯·瑞姆洛基",
			["IL"] = 18.3999996185303,
			["LastSeen"] = 1423318123,
			["Class"] = "PRIEST",
			["currency"] = {
				[402] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[789] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[395] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[697] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[776] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[823] = {
					["earnedThisWeek"] = 0,
				},
				[241] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[824] = {
					["earnedThisWeek"] = 0,
				},
				[515] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[390] = {
					["weeklyMax"] = 10700,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[391] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[752] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[392] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[777] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[738] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[416] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[396] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[81] = {
					["weeklyMax"] = 0,
					["earnedThisWeek"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[994] = {
					["earnedThisWeek"] = 0,
				},
			},
			["Level"] = 60,
			["LClass"] = "牧師",
			["RBGrating"] = 0,
			["PlayedTotal"] = 11576,
			["lastbossyelltime"] = 1423318021,
			["Money"] = 4054,
			["Show"] = "saved",
			["Zone"] = "奧格瑪",
			["PlayedLevel"] = 412,
			["Skills"] = {
			},
			["ILe"] = 18.3999996185303,
			["DailyResetTime"] = 1427914809,
			["Quests"] = {
			},
			["WeeklyResetTime"] = 1427914809,
		},
		["Patala - 冰風崗哨"] = {
			["lastbossyell"] = "北郡的瑪克西米利安",
			["WeeklyResetTime"] = 1427914809,
			["LastSeen"] = 1423322971,
			["Class"] = "MONK",
			["currency"] = {
				[402] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[789] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[395] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[697] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[776] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[823] = {
					["earnedThisWeek"] = 0,
				},
				[241] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[824] = {
					["earnedThisWeek"] = 0,
				},
				[515] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[390] = {
					["weeklyMax"] = 10700,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[391] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[752] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[392] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[777] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[738] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[416] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[396] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[81] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[994] = {
					["earnedThisWeek"] = 0,
				},
			},
			["Level"] = 50,
			["LClass"] = "武僧",
			["RBGrating"] = 0,
			["PlayedTotal"] = 28486,
			["lastbossyelltime"] = 1423322704,
			["Money"] = 2616155,
			["Show"] = "saved",
			["Zone"] = "安戈洛環形山",
			["PlayedLevel"] = 2874,
			["Skills"] = {
			},
			["ILe"] = 37,
			["DailyResetTime"] = 1427914809,
			["Quests"] = {
			},
			["IL"] = 37,
		},
		["Aalizzwall - 冰風崗哨"] = {
			["lastbossyell"] = "無頭騎士: 普通",
			["WeeklyResetTime"] = 1427914809,
			["LastSeen"] = 1422775025,
			["Class"] = "HUNTER",
			["currency"] = {
				[402] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[789] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[395] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[697] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[776] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[823] = {
					["earnedThisWeek"] = 0,
				},
				[241] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[824] = {
					["earnedThisWeek"] = 0,
				},
				[515] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[390] = {
					["weeklyMax"] = 9700,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[391] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[752] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[392] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[777] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[738] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[416] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[396] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[81] = {
					["weeklyMax"] = 0,
					["amount"] = 0,
					["totalMax"] = 0,
					["earnedThisWeek"] = 0,
				},
				[994] = {
					["earnedThisWeek"] = 0,
				},
			},
			["Level"] = 90,
			["LClass"] = "獵人",
			["RBGrating"] = 0,
			["PlayedTotal"] = 110572,
			["lastbossyelltime"] = 1414593084,
			["Money"] = 3009953,
			["Show"] = "saved",
			["IL"] = 490.600006103516,
			["PlayedLevel"] = 65936,
			["DailyResetTime"] = 1427914809,
			["ILe"] = 483,
			["Skills"] = {
			},
			["Quests"] = {
			},
			["Zone"] = "奧格瑪",
		},
		["Aalizz - 冰風崗哨"] = {
			["lastbossyell"] = "大賢者維瑞思: 普通",
			["WeeklyResetTime"] = 1427914809,
			["LastSeen"] = 1427899743,
			["Class"] = "DRUID",
			["currency"] = {
				[402] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 24,
				},
				[789] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[395] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[697] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 20,
					["amount"] = 7,
				},
				[776] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 20,
					["amount"] = 1,
				},
				[823] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 60000,
					["amount"] = 4436,
				},
				[241] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 3,
				},
				[824] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 10000,
					["amount"] = 3468,
				},
				[515] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 70,
				},
				[390] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 17575,
					["amount"] = 125,
					["season"] = "本季總共獲得：|cffffffff125",
					["totalMax"] = 0,
				},
				[391] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 86,
				},
				[752] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[392] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["amount"] = 440,
					["season"] = "本季總共獲得：|cffffffff177",
					["totalMax"] = 40,
				},
				[777] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 26102,
				},
				[738] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 367,
				},
				[416] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 0,
				},
				[396] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 10,
					["totalMax"] = 30,
					["amount"] = 0,
				},
				[81] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 0,
					["totalMax"] = 0,
					["amount"] = 55,
				},
				[994] = {
					["earnedThisWeek"] = 0,
					["weeklyMax"] = 3,
					["totalMax"] = 10,
					["amount"] = 2,
				},
			},
			["FarmPlanted"] = 0,
			["IL"] = 658.599975585938,
			["Level"] = 100,
			["LClass"] = "德魯伊",
			["RBGrating"] = 0,
			["Skills"] = {
			},
			["PlayedTotal"] = 4015028,
			["lastbosstime"] = 1423323844,
			["lastbossyelltime"] = 1423323844,
			["Money"] = 1122508125,
			["Zone"] = "霜牆要塞",
			["Show"] = "saved",
			["BonusRoll"] = {
				{
					["money"] = 216136,
					["name"] = "『活動山峰』泰克塔: 尋求團隊",
					["time"] = 1423237724,
					["currencyID"] = 994,
				}, -- [1]
				{
					["money"] = 203219,
					["name"] = "屠夫: 尋求團隊",
					["time"] = 1423235967,
					["currencyID"] = 994,
				}, -- [2]
				{
					["time"] = 1423235724,
					["name"] = "卡加斯‧刃拳: 尋求團隊",
					["item"] = "|cffa335ee|Hitem:116205:0:0:0:0:0:0:0:100:0:4:0|h[火行者足靴]|h|r",
					["currencyID"] = 994,
				}, -- [3]
				{
					["money"] = 290259,
					["time"] = 1423143697,
					["name"] = "魯克馬爾",
					["currencyID"] = 994,
				}, -- [4]
				{
					["money"] = 842884,
					["name"] = "傲慢之煞: 英雄",
					["time"] = 1416058991,
					["currencyID"] = 776,
				}, -- [5]
				{
					["time"] = 1416058493,
					["name"] = "諾努衫: 英雄",
					["item"] = "|cffa335ee|Hitem:112562:0:0:0:0:0:0:0:90:0:5:1:449|h[自信之握]|h|r",
					["currencyID"] = 776,
				}, -- [6]
				{
					["money"] = 250389,
					["name"] = "墮落的保衛者: 英雄",
					["time"] = 1416057275,
					["currencyID"] = 776,
				}, -- [7]
				{
					["money"] = 210061,
					["name"] = "伊莫爾西斯: 英雄",
					["time"] = 1416056696,
					["currencyID"] = 776,
				}, -- [8]
				{
					["money"] = 274642,
					["name"] = "卡爾洛斯·地獄吼: 英雄",
					["time"] = 1416054976,
					["currencyID"] = 776,
				}, -- [9]
				{
					["item"] = "|cffa335ee|Hitem:112940:0:0:0:0:0:0:0:90:0:3:0|h[亞煞拉懼的啟示]|h|r",
					["time"] = 1416029183,
					["name"] = "卡爾洛斯·地獄吼: 普通",
					["currencyID"] = 776,
				}, -- [10]
				{
					["money"] = 302394,
					["name"] = "傲慢之煞: 普通",
					["time"] = 1416024957,
					["currencyID"] = 776,
				}, -- [11]
				{
					["money"] = 966888,
					["name"] = "諾努衫: 普通",
					["time"] = 1416023968,
					["currencyID"] = 776,
				}, -- [12]
				{
					["item"] = "|cffa335ee|Hitem:112491:0:0:0:0:0:0:0:90:0:3:0|h[純淨之心蟋蟀籠]|h|r",
					["time"] = 1416023272,
					["name"] = "墮落的保衛者: 普通",
					["currencyID"] = 776,
				}, -- [13]
				{
					["money"] = 422169,
					["name"] = "伊莫爾西斯: 普通",
					["time"] = 1416022769,
					["currencyID"] = 776,
				}, -- [14]
				{
					["money"] = 153702,
					["name"] = "歐朵斯",
					["time"] = 1416022152,
					["currencyID"] = 776,
				}, -- [15]
				{
					["money"] = 177256,
					["name"] = "『嗜血巨龍』梭克: 普通",
					["time"] = 1415980242,
					["currencyID"] = 776,
				}, -- [16]
				{
					["money"] = 163025,
					["name"] = "上鎖的熊貓人寶箱: 普通",
					["time"] = 1415976931,
					["currencyID"] = 776,
				}, -- [17]
				{
					["money"] = 285241,
					["name"] = "馬可羅克: 普通",
					["time"] = 1415975816,
					["currencyID"] = 776,
				}, -- [18]
				{
					["name"] = "納茲格寧姆將軍: 普通",
					["item"] = "|cffa335ee|Hitem:99745:0:0:0:0:0:0:0:90:0:0:0|h[詛咒鎮壓者護手]|h|r",
					["time"] = 1415972247,
					["currencyID"] = 776,
				}, -- [19]
				{
					["money"] = 289923,
					["name"] = "柯爾克隆黑暗薩滿: 普通",
					["time"] = 1415970970,
					["currencyID"] = 776,
				}, -- [20]
				{
					["money"] = 361177,
					["name"] = "鋼鐵破滅邪神: 普通",
					["time"] = 1415969657,
					["currencyID"] = 776,
				}, -- [21]
				{
					["money"] = 254685,
					["name"] = "葛拉卡斯: 普通",
					["time"] = 1415968605,
					["currencyID"] = 776,
				}, -- [22]
				{
					["money"] = 336755,
					["name"] = "玉龍",
					["time"] = 1415890888,
					["currencyID"] = 776,
				}, -- [23]
				{
					["time"] = 1414819099,
					["name"] = "伊莫爾西斯: 尋求團隊",
					["item"] = "|cffa335ee|Hitem:112427:0:0:0:0:0:0:0:90:0:4:1:451|h[永恆哀傷徽印]|h|r",
					["currencyID"] = 776,
				}, -- [24]
				{
					["money"] = 950022,
					["time"] = 1414811852,
					["name"] = "鋼鐵破滅邪神: 尋求團隊",
					["currencyID"] = 776,
				}, -- [25]
			},
			["PlayedLevel"] = 644007,
			["lastboss"] = "大賢者維瑞思: 普通",
			["ILe"] = 658.266662597656,
			["DailyResetTime"] = 1427914809,
			["Quests"] = {
				[36058] = {
					["Expires"] = 1427914809,
					["Title"] = "Seal of Tempered Fate: Armory",
					["Link"] = "|cffffff00|Hquest:36058:90|h[Seal of Tempered Fate: Armory]|h|r",
				},
			},
			["FarmHarvested"] = 0,
		},
	},
	["Tooltip"] = {
		["CategorySort"] = "EXPANSION",
		["ShowSoloCategory"] = false,
		["ShowServer"] = false,
		["ShowExpired"] = false,
		["RaidsFirst"] = true,
		["posy"] = 311.500122070313,
		["CombineWorldBosses"] = false,
		["HistoryText"] = false,
		["ShowCategories"] = false,
		["Currency738"] = true,
		["CurrencyEarned"] = true,
		["Currency776"] = true,
		["CurrencyValueColor"] = true,
		["Details"] = false,
		["Currency994"] = true,
		["TrackWeeklyQuests"] = true,
		["CombineLFR"] = true,
		["LimitWarn"] = true,
		["RowHighlight"] = 0.1,
		["Currency824"] = true,
		["ShowHoliday"] = true,
		["ServerOnly"] = false,
		["TrackLFG"] = true,
		["ReverseInstances"] = false,
		["TrackDailyQuests"] = true,
		["Currency823"] = true,
		["Scale"] = 1,
		["ShowRandom"] = true,
		["TrackFarm"] = true,
		["SelfFirst"] = true,
		["Currency395"] = false,
		["AugmentBonus"] = true,
		["ServerSort"] = true,
		["posx"] = 604.5,
		["ColumnStyle"] = "NORMAL",
		["Currency396"] = false,
		["CurrencyMax"] = false,
		["TrackDeserter"] = true,
		["NewFirst"] = true,
		["SelfAlways"] = false,
		["TrackSkills"] = true,
		["ShowHints"] = true,
		["ReportResets"] = true,
		["AltColumnColor"] = {
			0.2, -- [1]
			0.2, -- [2]
			0.2, -- [3]
			1, -- [4]
		},
		["CategorySpaces"] = false,
	},
	["Instances"] = {
		["圍攻怒兆寺"] = {
			["LFDID"] = 630,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 89,
			["Raid"] = false,
		},
		["黑曜聖所"] = {
			["LFDID"] = 238,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["恐懼之心"] = {
			["LFDID"] = 534,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["黑石塔下層"] = {
			["LFDID"] = 32,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 58,
		},
		["十字軍試煉"] = {
			["LFDID"] = 248,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["影月墓地"] = {
			["LFDID"] = 784,
			["Expansion"] = 5,
			["Show"] = "saved",
			["RecLevel"] = 100,
			["Raid"] = false,
		},
		["隨機浩劫與重生地城"] = {
			["LFDID"] = 300,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 0,
		},
		["黑石深淵 - 禁閉室"] = {
			["LFDID"] = 30,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 51,
		},
		["隨機浩劫與重生英雄"] = {
			["LFDID"] = 301,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 0,
		},
		["黑澗深淵"] = {
			["LFDID"] = 10,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 24,
		},
		["瑪瑟里頓的巢穴"] = {
			["LFDID"] = 176,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["毒蛇神殿洞穴"] = {
			["LFDID"] = 194,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["斯坦索姆 - 僕從入口"] = {
			["LFDID"] = 274,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 50,
		},
		["團隊搜尋器: 秘法寶庫"] = {
			["LFDID"] = 831,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["天槌"] = {
			["LFDID"] = 897,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
				[14] = {
					["Expires"] = 0,
					["Extended"] = false,
					["Link"] = "|cffff8000|Hinstancelock:Player-964-04165708:1228:14:64|h[天槌]|h|r",
					["ID"] = 504816220,
					["Locked"] = false,
				},
				[15] = {
					["Expires"] = 0,
					["Extended"] = false,
					["Link"] = "|cffff8000|Hinstancelock:Player-964-04165708:1228:15:62|h[天槌]|h|r",
					["ID"] = 517449931,
					["Locked"] = false,
				},
			},
			["RecLevel"] = 100,
			["Raid"] = true,
		},
		["麥克納爾"] = {
			["LFDID"] = 192,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 68,
			["Raid"] = false,
		},
		["隨機潘達利亞之謎英雄事件"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["Scenario"] = true,
			["LFDID"] = 641,
			["RecLevel"] = 0,
			["Random"] = true,
			["Raid"] = false,
		},
		["熔火之心"] = {
			["LFDID"] = 48,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 60,
		},
		["隨機潘達利亞之謎地城"] = {
			["LFDID"] = 463,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 0,
		},
		["隨機巫妖王地城"] = {
			["LFDID"] = 261,
			["Expansion"] = 2,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 80,
		},
		["團隊搜尋器: 黑手的考驗"] = {
			["LFDID"] = 823,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 100,
		},
		["祖爾法拉克"] = {
			["LFDID"] = 24,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 48,
		},
		["亞夏梵穹殿"] = {
			["LFDID"] = 240,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["總大使弗萊拉斯"] = {
			["Show"] = "saved",
			["Expansion"] = 0,
			["LFDID"] = 308,
			["RecLevel"] = 80,
			["Holiday"] = true,
			["Raid"] = false,
		},
		["斯坦索姆的抉擇"] = {
			["LFDID"] = 210,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["巨龍之魂"] = {
			["LFDID"] = 448,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["卡拉贊"] = {
			["LFDID"] = 175,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["團隊搜尋器: 恆憂谷"] = {
			["LFDID"] = 839,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["團隊搜尋器: 壁壘之城"] = {
			["LFDID"] = 849,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["Raid"] = true,
			["RecLevel"] = 100,
		},
		["憤怒之煞"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["WorldBoss"] = 691,
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["沉沒的神廟"] = {
			["LFDID"] = 28,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 54,
		},
		["團隊搜尋器: 杉齊爾的夢魘"] = {
			["LFDID"] = 833,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["團隊搜尋器: 遺忘深淵"] = {
			["LFDID"] = 836,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["斯坦索姆 - 主門"] = {
			["LFDID"] = 40,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 46,
		},
		["冰冠城塞"] = {
			["LFDID"] = 280,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["團隊搜尋器: 地下要塞"] = {
			["LFDID"] = 841,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["奧達曼"] = {
			["LFDID"] = 22,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 39,
		},
		["剃刀高地"] = {
			["LFDID"] = 20,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 44,
		},
		["隨機潘達利亞之謎事件"] = {
			["LFDID"] = 493,
			["Expansion"] = 4,
			["Scenario"] = true,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 0,
		},
		["開啟黑暗之門"] = {
			["LFDID"] = 182,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 70,
			["Raid"] = false,
		},
		["德拉克薩隆要塞"] = {
			["LFDID"] = 215,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 75,
			["Raid"] = false,
		},
		["薩爾撒倫王子"] = {
			["Show"] = "saved",
			["Expansion"] = 0,
			["LFDID"] = 310,
			["RecLevel"] = 80,
			["Holiday"] = true,
			["Raid"] = false,
		},
		["薩倫之淵"] = {
			["LFDID"] = 254,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["雷光大廳"] = {
			["LFDID"] = 212,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["波塔尼卡"] = {
			["LFDID"] = 191,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 70,
			["Raid"] = false,
		},
		["法力墓地"] = {
			["LFDID"] = 179,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 65,
			["Raid"] = false,
		},
		["破碎大廳"] = {
			["LFDID"] = 189,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 70,
			["Raid"] = false,
		},
		["黑翼之巢"] = {
			["LFDID"] = 50,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 60,
		},
		["帆船"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["WorldBoss"] = 725,
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["瑪拉頓 - 邪惡洞穴"] = {
			["LFDID"] = 272,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 34,
		},
		["無頭騎士"] = {
			["Show"] = "saved",
			["Expansion"] = 0,
			["LFDID"] = 285,
			["RecLevel"] = 90,
			["Holiday"] = true,
			["Raid"] = false,
		},
		["女王儲瑟萊德絲公主"] = {
			["Show"] = "saved",
			["Expansion"] = 0,
			["LFDID"] = 309,
			["RecLevel"] = 80,
			["Holiday"] = true,
			["Raid"] = false,
		},
		["托維爾的失落之城"] = {
			["LFDID"] = 325,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 84,
			["Raid"] = false,
		},
		["起源大廳"] = {
			["LFDID"] = 321,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = false,
		},
		["歐朵斯"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["WorldBoss"] = 861,
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["納克薩瑪斯"] = {
			["LFDID"] = 227,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["奧奇奈地穴"] = {
			["LFDID"] = 178,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 66,
			["Raid"] = false,
		},
		["安其拉神廟"] = {
			["LFDID"] = 161,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 60,
		},
		["勇士試煉"] = {
			["LFDID"] = 249,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["影潘僧院"] = {
			["LFDID"] = 470,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 88,
			["Raid"] = false,
		},
		["黑暗神廟"] = {
			["LFDID"] = 196,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["阿茲歐-奈幽"] = {
			["LFDID"] = 241,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 74,
			["Raid"] = false,
		},
		["黑翼陷窟"] = {
			["LFDID"] = 314,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["俄特加德要塞"] = {
			["LFDID"] = 242,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 72,
			["Raid"] = false,
		},
		["隨機艾澤拉斯地城"] = {
			["LFDID"] = 258,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 55,
		},
		["諾姆瑞根"] = {
			["LFDID"] = 14,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 28,
		},
		["團隊搜尋器: 死亡之翼隕落"] = {
			["LFDID"] = 844,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["厄運之槌 - 戈多克平民區"] = {
			["LFDID"] = 38,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 46,
		},
		["哀嚎洞穴"] = {
			["LFDID"] = 1,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 19,
		},
		["漩渦尖塔"] = {
			["LFDID"] = 319,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 83,
			["Raid"] = false,
		},
		["四風王座"] = {
			["LFDID"] = 318,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["隨機暮光之時英雄"] = {
			["LFDID"] = 434,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 0,
		},
		["團隊搜尋器: 風暴之巔"] = {
			["LFDID"] = 838,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["黑石鑄造場"] = {
			["LFDID"] = 900,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
				[14] = {
					["Expires"] = 0,
					["Extended"] = false,
					["Link"] = "|cffff8000|Hinstancelock:Player-964-04165708:1205:14:16|h[黑石鑄造場]|h|r",
					["ID"] = 511573082,
					["Locked"] = false,
				},
			},
			["RecLevel"] = 100,
			["Raid"] = true,
		},
		["隨機巫妖王英雄"] = {
			["LFDID"] = 262,
			["Expansion"] = 2,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 80,
		},
		["團隊搜尋器: 熔渣處理場"] = {
			["LFDID"] = 847,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 100,
		},
		["塞司克大廳"] = {
			["LFDID"] = 180,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 68,
			["Raid"] = false,
		},
		["血色修道院"] = {
			["LFDID"] = 474,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 32,
			["Raid"] = false,
		},
		["火源之界"] = {
			["LFDID"] = 362,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["豐泉台"] = {
			["LFDID"] = 536,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["祖阿曼"] = {
			["LFDID"] = 340,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 85,
		},
		["影牙城堡"] = {
			["LFDID"] = 327,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 20,
			["Raid"] = false,
		},
		["魔古山宮"] = {
			["LFDID"] = 519,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 88,
			["Raid"] = false,
		},
		["通靈學院"] = {
			["LFDID"] = 472,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 42,
			["Raid"] = false,
		},
		["魯克馬爾"] = {
			["Show"] = "saved",
			["Expansion"] = 5,
			["WorldBoss"] = 1262,
			["Aalizz - 冰風崗哨"] = {
				[2] = {
					true, -- [1]
					["ID"] = -1,
					["Expires"] = 1427914807,
				},
			},
			["RecLevel"] = 100,
			["Raid"] = true,
		},
		["奧核之眼"] = {
			["LFDID"] = 211,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["血色大廳"] = {
			["LFDID"] = 473,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 30,
			["Raid"] = false,
		},
		["團隊搜尋器: 霸權隕落"] = {
			["LFDID"] = 842,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["暴風城監獄"] = {
			["LFDID"] = 12,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 24,
		},
		["巴拉丁堡"] = {
			["LFDID"] = 329,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["俄特加德之巔"] = {
			["LFDID"] = 205,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["團隊搜尋器: 豐泉台"] = {
			["LFDID"] = 834,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["倒影大廳"] = {
			["LFDID"] = 256,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["海潮王座"] = {
			["LFDID"] = 324,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 81,
			["Raid"] = false,
		},
		["黑石洞穴"] = {
			["LFDID"] = 323,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 81,
			["Raid"] = false,
		},
		["亞克崔茲"] = {
			["LFDID"] = 190,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 70,
			["Raid"] = false,
		},
		["戈魯爾之巢"] = {
			["LFDID"] = 177,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["剃刀沼澤"] = {
			["LFDID"] = 16,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 34,
		},
		["地獄火壁壘"] = {
			["LFDID"] = 188,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 61,
			["Raid"] = false,
		},
		["四大天尊"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["WorldBoss"] = 857,
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["太陽之井"] = {
			["LFDID"] = 199,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["終焉之刻"] = {
			["LFDID"] = 435,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 85,
		},
		["瑪拉頓 - 毒菇洞穴"] = {
			["LFDID"] = 26,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 36,
		},
		["血槌熔渣礦場"] = {
			["LFDID"] = 859,
			["Expansion"] = 5,
			["Show"] = "saved",
			["RecLevel"] = 91,
			["Raid"] = false,
		},
		["冰霜領主艾胡恩"] = {
			["Show"] = "saved",
			["Expansion"] = 1,
			["LFDID"] = 286,
			["RecLevel"] = 100,
			["Holiday"] = true,
			["Raid"] = false,
		},
		["奧妮克希亞的巢穴"] = {
			["LFDID"] = 257,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["擎天峰"] = {
			["LFDID"] = 780,
			["Expansion"] = 5,
			["Show"] = "saved",
			["RecLevel"] = 98,
			["Raid"] = false,
		},
		["團隊搜尋器: 懲戒之門"] = {
			["LFDID"] = 840,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["死亡礦坑"] = {
			["LFDID"] = 326,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 16,
			["Raid"] = false,
		},
		["黑石深淵 - 上城區"] = {
			["LFDID"] = 276,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 55,
		},
		["安其拉廢墟"] = {
			["LFDID"] = 160,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 60,
		},
		["凱祖·加茲瑞拉"] = {
			["Show"] = "saved",
			["Expansion"] = 0,
			["LFDID"] = 306,
			["RecLevel"] = 80,
			["Holiday"] = true,
			["Raid"] = false,
		},
		["眾魂熔爐"] = {
			["LFDID"] = 252,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = false,
		},
		["隨機德拉諾之霸英雄地城"] = {
			["Show"] = "saved",
			["Expansion"] = 5,
			["LFDID"] = 789,
			["RecLevel"] = 0,
			["Random"] = true,
			["Raid"] = false,
		},
		["大十字軍試煉"] = {
			["LFDID"] = 250,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["厄運之槌 - 扭木廣場"] = {
			["LFDID"] = 34,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 40,
		},
		["鋼鐵碼頭"] = {
			["LFDID"] = 857,
			["Expansion"] = 5,
			["Show"] = "saved",
			["RecLevel"] = 93,
			["Raid"] = false,
		},
		["暮光之時"] = {
			["LFDID"] = 439,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 85,
		},
		["永恆之井"] = {
			["LFDID"] = 437,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 85,
		},
		["團隊搜尋器: 秘法聖所"] = {
			["LFDID"] = 850,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["Raid"] = true,
			["RecLevel"] = 100,
		},
		["團隊搜尋器: 鋼鐵集貨區"] = {
			["LFDID"] = 848,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
				[2] = {
					false, -- [1]
					false, -- [2]
					false, -- [3]
					true, -- [4]
					false, -- [5]
					true, -- [6]
					false, -- [7]
					false, -- [8]
					true, -- [9]
					false, -- [10]
					["ID"] = -10,
					["Expires"] = 1427914807,
				},
			},
			["Raid"] = true,
			["RecLevel"] = 100,
		},
		["逃離敦霍爾德"] = {
			["LFDID"] = 183,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 67,
			["Raid"] = false,
		},
		["落陽關"] = {
			["LFDID"] = 631,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = false,
		},
		["團隊搜尋器: 圍攻龍眠神殿"] = {
			["LFDID"] = 843,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["魔古山寶庫"] = {
			["LFDID"] = 532,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["奧齊頓"] = {
			["LFDID"] = 845,
			["Expansion"] = 5,
			["Show"] = "saved",
			["RecLevel"] = 96,
			["Raid"] = false,
		},
		["團隊搜尋器: 恐懼門徑"] = {
			["LFDID"] = 832,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["風暴要塞"] = {
			["LFDID"] = 193,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["過往的海加爾山"] = {
			["LFDID"] = 195,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = true,
			["RecLevel"] = 70,
		},
		["石岩之心"] = {
			["LFDID"] = 320,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 83,
			["Raid"] = false,
		},
		["恐軌車站"] = {
			["LFDID"] = 858,
			["Expansion"] = 5,
			["Show"] = "saved",
			["RecLevel"] = 100,
			["Raid"] = false,
		},
		["永茂林"] = {
			["LFDID"] = 866,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
				[2] = {
					["Expires"] = 0,
					["Extended"] = false,
					["Link"] = "|cffff8000|Hinstancelock:Player-964-04165708:1279:2:27|h[永茂林]|h|r",
					["ID"] = 515215031,
					["Locked"] = false,
				},
			},
			["RecLevel"] = 100,
			["Raid"] = false,
		},
		["團隊搜尋器: 魔古山的守護者"] = {
			["LFDID"] = 830,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["剛德拉克"] = {
			["LFDID"] = 217,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 78,
			["Raid"] = false,
		},
		["雷霆王座"] = {
			["LFDID"] = 634,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["怒焰裂谷"] = {
			["LFDID"] = 4,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 16,
		},
		["隨機德拉諾之霸地城"] = {
			["LFDID"] = 788,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 0,
		},
		["團隊搜尋器: 統治者之臺"] = {
			["LFDID"] = 851,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["Raid"] = true,
			["RecLevel"] = 100,
		},
		["奴隸監獄"] = {
			["LFDID"] = 184,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 63,
			["Raid"] = false,
		},
		["安卡罕特:古王國"] = {
			["LFDID"] = 219,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 75,
			["Raid"] = false,
		},
		["博學者殿堂"] = {
			["LFDID"] = 201,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 68,
			["Raid"] = false,
		},
		["晶紅聖所"] = {
			["LFDID"] = 294,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["隨機時光行者地城"] = {
			["LFDID"] = 744,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 0,
		},
		["瑪拉頓 - 地歌瀑布"] = {
			["LFDID"] = 273,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 38,
		},
		["格瑞姆巴托"] = {
			["LFDID"] = 322,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 84,
			["Raid"] = false,
		},
		["奧核之心"] = {
			["LFDID"] = 226,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 73,
			["Raid"] = false,
		},
		["隨機燃燒的遠征地城"] = {
			["LFDID"] = 259,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 65,
		},
		["奧杜亞"] = {
			["LFDID"] = 244,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["厄運之槌 - 中心花園"] = {
			["LFDID"] = 36,
			["Expansion"] = 0,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 43,
		},
		["深幽泥沼"] = {
			["LFDID"] = 186,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 64,
			["Raid"] = false,
		},
		["血熔爐"] = {
			["LFDID"] = 187,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 62,
			["Raid"] = false,
		},
		["祖爾格拉布"] = {
			["LFDID"] = 334,
			["Expansion"] = 3,
			["Show"] = "saved",
			["Raid"] = false,
			["RecLevel"] = 85,
		},
		["隨機潘達利亞之謎英雄"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["LFDID"] = 462,
			["RecLevel"] = 0,
			["Random"] = true,
			["Raid"] = false,
		},
		["團隊搜尋器: 血肉塑形大廳"] = {
			["LFDID"] = 837,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["石之大廳"] = {
			["LFDID"] = 213,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 78,
			["Raid"] = false,
		},
		["風暴烈酒酒坊"] = {
			["LFDID"] = 469,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 86,
			["Raid"] = false,
		},
		["圍攻奧格瑪"] = {
			["LFDID"] = 766,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["永恆之眼"] = {
			["LFDID"] = 237,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 80,
			["Raid"] = true,
		},
		["紫羅蘭堡"] = {
			["LFDID"] = 221,
			["Expansion"] = 2,
			["Show"] = "saved",
			["RecLevel"] = 76,
			["Raid"] = false,
		},
		["隨機燃燒的遠征英雄模式"] = {
			["LFDID"] = 260,
			["Expansion"] = 1,
			["Show"] = "saved",
			["Raid"] = false,
			["Random"] = true,
			["RecLevel"] = 70,
		},
		["暗影迷宮"] = {
			["LFDID"] = 181,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 70,
			["Raid"] = false,
		},
		["團隊搜尋器: 贊達拉的最後防線"] = {
			["LFDID"] = 835,
			["Expansion"] = 4,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
			},
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["王冠化學製藥公司"] = {
			["Show"] = "saved",
			["Expansion"] = 0,
			["Raid"] = false,
			["RecLevel"] = 100,
			["Holiday"] = true,
			["LFDID"] = 288,
		},
		["玉蛟寺"] = {
			["LFDID"] = 468,
			["Expansion"] = 4,
			["Show"] = "saved",
			["RecLevel"] = 86,
			["Raid"] = false,
		},
		["寇仁·恐酒"] = {
			["Show"] = "saved",
			["Expansion"] = 0,
			["LFDID"] = 287,
			["RecLevel"] = 90,
			["Holiday"] = true,
			["Raid"] = false,
		},
		["納拉卡"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["WorldBoss"] = 814,
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["烏達斯塔"] = {
			["Show"] = "saved",
			["Expansion"] = 4,
			["WorldBoss"] = 826,
			["RecLevel"] = 90,
			["Raid"] = true,
		},
		["蒸汽洞窟"] = {
			["LFDID"] = 185,
			["Expansion"] = 1,
			["Show"] = "saved",
			["RecLevel"] = 70,
			["Raid"] = false,
		},
		["團隊搜尋器: 黑熔爐"] = {
			["LFDID"] = 846,
			["Expansion"] = 5,
			["Show"] = "saved",
			["Aalizz - 冰風崗哨"] = {
				[2] = {
					false, -- [1]
					false, -- [2]
					false, -- [3]
					false, -- [4]
					false, -- [5]
					false, -- [6]
					false, -- [7]
					true, -- [8]
					false, -- [9]
					false, -- [10]
					["ID"] = -10,
					["Expires"] = 1427914807,
				},
			},
			["Raid"] = true,
			["RecLevel"] = 100,
		},
		["暮光堡壘"] = {
			["LFDID"] = 316,
			["Expansion"] = 3,
			["Show"] = "saved",
			["RecLevel"] = 85,
			["Raid"] = true,
		},
		["『毀滅者』德羅夫 / 『不朽者』塔爾納"] = {
			["Show"] = "saved",
			["Expansion"] = 5,
			["WorldBoss"] = 1211,
			["RecLevel"] = 100,
			["Raid"] = true,
		},
		["黑石塔上層"] = {
			["LFDID"] = 860,
			["Expansion"] = 5,
			["Raid"] = false,
			["RecLevel"] = 90,
			["Show"] = "saved",
		},
	},
	["spelltip"] = {
		[71041] = {
			"地城逃亡者", -- [1]
			"你離開了你的隊伍，因此必須等待一段時間才能再次使用地城搜尋器跟團隊搜尋器。", -- [2]
		},
	},
	["History"] = {
	},
	["Indicators"] = {
		["R2ClassColor"] = true,
		["D2Indicator"] = "BLANK",
		["R7Color"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["R5Color"] = {
			0, -- [1]
			0, -- [2]
			1, -- [3]
		},
		["R1Text"] = "KILLED/TOTAL",
		["R4Indicator"] = "BLANK",
		["R1Color"] = {
			0.6, -- [1]
			0.6, -- [2]
			0, -- [3]
		},
		["R0Indicator"] = "BLANK",
		["R8ClassColor"] = true,
		["D2ClassColor"] = true,
		["R4ClassColor"] = true,
		["R6ClassColor"] = true,
		["D2Color"] = {
			0, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["D1Text"] = "KILLED/TOTAL",
		["D1Indicator"] = "BLANK",
		["R8Color"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["R0ClassColor"] = true,
		["R6Color"] = {
			0, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["R1ClassColor"] = true,
		["R4Color"] = {
			1, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["R2Indicator"] = "BLANK",
		["R2Text"] = "KILLED/TOTAL",
		["R7Indicator"] = "BLANK",
		["R0Text"] = "KILLED/TOTAL",
		["R0Color"] = {
			0.6, -- [1]
			0.6, -- [2]
			0, -- [3]
		},
		["D2Text"] = "KILLED/TOTAL",
		["R1Indicator"] = "BLANK",
		["R2Color"] = {
			0.6, -- [1]
			0, -- [2]
			0, -- [3]
		},
		["R7ClassColor"] = true,
		["R3Color"] = {
			1, -- [1]
			1, -- [2]
			0, -- [3]
		},
		["D1ClassColor"] = true,
		["R3Text"] = "KILLED/TOTALH",
		["R5Indicator"] = "BLANK",
		["R3ClassColor"] = true,
		["R4Text"] = "KILLED/TOTALH",
		["R5ClassColor"] = true,
		["R5Text"] = "KILLED/TOTAL",
		["R8Indicator"] = "BLANK",
		["R6Text"] = "KILLED/TOTAL",
		["D1Color"] = {
			0, -- [1]
			0.6, -- [2]
			0, -- [3]
		},
		["R3Indicator"] = "BLANK",
		["R8Text"] = "KILLED/TOTALM",
		["R7Text"] = "KILLED/TOTALH",
		["R6Indicator"] = "BLANK",
	},
	["DailyResetTime"] = 1427914809,
	["QuestDB"] = {
		["Daily"] = {
			[28682] = 709,
			[30335] = 807,
			[30337] = 807,
			[28690] = 709,
			[28692] = 709,
			[28694] = 709,
			[28696] = 709,
			[30476] = 807,
			[30478] = 807,
			[32643] = 807,
			[32647] = 807,
			[32649] = 807,
			[32653] = 807,
			[30242] = 811,
			[32657] = 807,
			[28700] = 709,
			[29377] = 382,
			[32943] = 807,
			[36697] = 976,
			[28681] = 709,
			[29375] = 382,
			[30266] = 811,
			[30473] = 807,
			[31288] = 811,
			[30147] = 806,
			[30151] = 806,
			[30323] = 807,
			[33146] = 807,
			[30474] = 807,
			[28680] = 709,
			[28678] = 709,
			[31443] = 857,
			[30327] = 807,
			[30325] = 807,
			[30306] = 811,
			[28657] = 708,
			[28659] = 708,
			[28661] = 708,
			[28663] = 708,
			[28665] = 708,
			[30318] = 807,
			[28669] = 708,
			[30322] = 807,
			[30324] = 807,
			[30326] = 807,
			[30328] = 807,
			[28679] = 709,
			[30332] = 807,
			[30334] = 807,
			[28685] = 709,
			[28687] = 709,
			[28689] = 709,
			[28691] = 709,
			[29455] = 823,
			[28695] = 709,
			[28697] = 709,
			[24635] = 321,
			[29463] = 823,
			[32642] = 807,
			[28670] = 708,
			[28668] = 708,
			[32648] = 807,
			[32650] = 807,
			[30472] = 807,
			[28664] = 708,
			[36481] = 823,
			[36695] = 976,
			[11219] = 20,
			[29438] = 823,
			[30330] = 807,
			[30475] = 807,
			[28698] = 709,
			[30261] = 811,
			[29374] = 382,
			[29376] = 382,
			[28693] = 709,
			[33358] = 807,
			[30333] = 807,
			[28686] = 709,
			[31291] = 811,
			[30277] = 811,
			[30243] = 811,
			[30471] = 807,
			[36688] = 976,
			[28683] = 709,
			[30336] = 807,
			[31675] = 807,
			[28935] = 321,
			[12155] = 4,
			[24636] = 321,
			[28684] = 709,
			[31446] = 857,
			[31704] = 806,
			[28658] = 708,
			[28660] = 708,
			[28662] = 708,
			[32942] = 807,
			[30317] = 807,
			[30319] = 807,
			[30321] = 807,
			[29434] = 823,
			[29436] = 823,
			[24612] = 321,
			[30329] = 807,
			[30331] = 807,
			[30470] = 807,
		},
		["Darkmoon"] = {
			[29509] = 823,
			[29513] = 823,
			[33354] = 823,
			[29514] = 823,
			["expires"] = 1428854340,
			[29507] = 823,
			[29515] = 823,
			[29433] = 823,
			[29512] = 823,
		},
		["AccountDaily"] = {
			[31752] = 903,
			[34774] = 941,
		},
		["Weekly"] = {
			[32640] = 862,
			["expires"] = 1427914807,
			[32641] = 862,
			[36054] = 1011,
			[36055] = 1011,
			[36056] = 1011,
			[37452] = -1,
			[37453] = -1,
			[37454] = -1,
			[37455] = -1,
			[37456] = 1011,
			[33334] = 862,
			[37458] = -1,
			[37459] = -1,
			[36057] = -1,
			[33338] = 862,
			[28884] = 709,
			[31876] = 806,
			[36058] = -1,
			[37457] = -1,
		},
		["AccountWeekly"] = {
			["expires"] = 1427914807,
		},
	},
	["histGeneration"] = 319,
	["Quests"] = {
	},
	["MinimapIcon"] = {
		["minimapPos"] = 239.743494953154,
		["hide"] = true,
	},
}
