
SIL_Settings = {
	["global"] = {
		["version"] = 3,
	},
	["profileKeys"] = {
		["Aalizz - 冰風崗哨"] = "Default",
	},
}
SIL_CacheGUID = {
	["Player-964-02BD13CD"] = {
		["items"] = false,
		["time"] = false,
		["name"] = "Easonfiona",
		["score"] = false,
		["target"] = "raid14",
		["class"] = "PALADIN",
		["level"] = 100,
		["realm"] = "寒冰皇冠",
	},
	["Player-964-02B9A6CA"] = {
		["items"] = false,
		["name"] = "段紹祥",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid12",
		["class"] = "SHAMAN",
		["score"] = false,
		["realm"] = "寒冰皇冠",
	},
	["Player-964-000F0B6B"] = {
		["items"] = false,
		["name"] = "Cwkiminn",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid11",
		["class"] = "ROGUE",
		["score"] = false,
		["realm"] = "尖石",
	},
	["Player-964-003650A1"] = {
		["items"] = false,
		["time"] = false,
		["name"] = "昕甯",
		["score"] = false,
		["target"] = "raid20",
		["class"] = "MAGE",
		["level"] = 100,
		["realm"] = "尖石",
	},
	["Player-964-03E3667B"] = {
		["items"] = false,
		["name"] = "泰蘭妲的玫瑰",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid14",
		["class"] = "WARLOCK",
		["score"] = false,
		["realm"] = "",
	},
	["Player-964-022F3CB9"] = {
		["items"] = false,
		["time"] = false,
		["name"] = "為什麼北投",
		["score"] = false,
		["target"] = "raid14",
		["class"] = "PALADIN",
		["level"] = 100,
		["realm"] = "尖石",
	},
	["Player-978-028EE123"] = {
		["items"] = false,
		["name"] = "壓到我頭髮了",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid9",
		["class"] = "WARRIOR",
		["score"] = false,
		["realm"] = "日落沼澤",
	},
	["Player-999-02FC80FB"] = {
		["items"] = false,
		["name"] = "雷霆木蝸牛奶",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid16",
		["class"] = "MAGE",
		["score"] = false,
		["realm"] = "地獄吼",
	},
	["Player-985-0447A33B"] = {
		["items"] = false,
		["name"] = "神之腳指",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid15",
		["class"] = "HUNTER",
		["score"] = false,
		["realm"] = "水晶之刺",
	},
	["Player-985-04378316"] = {
		["items"] = false,
		["name"] = "番茄牛肉麵",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid3",
		["class"] = "PALADIN",
		["score"] = false,
		["realm"] = "憤怒使者",
	},
	["Player-964-0417245D"] = {
		["items"] = false,
		["name"] = "加啡貓",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid17",
		["class"] = "DRUID",
		["score"] = false,
		["realm"] = "寒冰皇冠",
	},
	["Player-978-003A34D7"] = {
		["items"] = false,
		["name"] = "美女座騎",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid13",
		["class"] = "MAGE",
		["score"] = false,
		["realm"] = "日落沼澤",
	},
	["Player-964-04343905"] = {
		["items"] = false,
		["name"] = "今晚被老唬打",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid14",
		["class"] = "DEATHKNIGHT",
		["score"] = false,
		["realm"] = "寒冰皇冠",
	},
	["Player-964-03E36224"] = {
		["items"] = false,
		["name"] = "嗚嗚哥哥",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid20",
		["class"] = "PALADIN",
		["score"] = false,
		["realm"] = "",
	},
	["Player-964-03E35E2C"] = {
		["items"] = false,
		["name"] = "凜仒凍",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid8",
		["class"] = "DEATHKNIGHT",
		["score"] = false,
		["realm"] = "",
	},
	["Player-964-00113A8A"] = {
		["items"] = false,
		["name"] = "象形文",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid18",
		["class"] = "WARRIOR",
		["score"] = false,
		["realm"] = "尖石",
	},
	["Player-964-03D0A8FE"] = {
		["items"] = false,
		["name"] = "訕笑骷髏",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid4",
		["class"] = "SHAMAN",
		["score"] = false,
		["realm"] = "",
	},
	["Player-964-00955F00"] = {
		["score"] = 659.066666666667,
		["class"] = "HUNTER",
		["items"] = 15,
		["resil"] = 0,
		["time"] = 1427895846,
		["target"] = "raid1",
		["level"] = 100,
		["name"] = "過路獵人",
		["realm"] = "尖石",
	},
	["Player-964-03D10C9C"] = {
		["items"] = false,
		["name"] = "狩魔行者",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid14",
		["class"] = "HUNTER",
		["score"] = false,
		["realm"] = "",
	},
	["Player-964-0421BC51"] = {
		["items"] = false,
		["name"] = "梓洛丶",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid6",
		["class"] = "PRIEST",
		["score"] = false,
		["realm"] = "尖石",
	},
	["Player-964-03D198C0"] = {
		["items"] = false,
		["name"] = "江南一憶",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid5",
		["class"] = "ROGUE",
		["score"] = false,
		["realm"] = "",
	},
	["Player-978-02CDA53A"] = {
		["items"] = false,
		["time"] = false,
		["name"] = "Stanrey",
		["score"] = false,
		["target"] = "raid21",
		["class"] = "WARRIOR",
		["level"] = 100,
		["realm"] = "屠魔山谷",
	},
	["Player-964-0424E3A1"] = {
		["score"] = 666.3125,
		["class"] = "DRUID",
		["items"] = 16,
		["resil"] = 0,
		["name"] = "奧格瑪腦公",
		["target"] = "raid22",
		["level"] = 100,
		["time"] = 1427895987,
		["realm"] = "尖石",
	},
	["Player-964-03CCAF22"] = {
		["score"] = 614.3125,
		["class"] = "ROGUE",
		["items"] = 16,
		["resil"] = 0,
		["name"] = "背後小心啊",
		["target"] = "raid14",
		["level"] = 100,
		["time"] = 1427895931,
		["realm"] = "冰風崗哨",
	},
	["Player-964-02BAFB65"] = {
		["score"] = 661,
		["class"] = "DRUID",
		["items"] = 15,
		["resil"] = 0,
		["name"] = "就是不補",
		["target"] = "raid20",
		["level"] = 100,
		["time"] = 1427895734,
		["realm"] = "寒冰皇冠",
	},
	["Player-964-03CF52FE"] = {
		["score"] = 686.933333333333,
		["class"] = "DEATHKNIGHT",
		["items"] = 15,
		["resil"] = 0,
		["name"] = "暗黑茶葉蛋",
		["target"] = "raid21",
		["level"] = 100,
		["time"] = 1427895722,
		["realm"] = "",
	},
	["Player-985-028F7D71"] = {
		["score"] = 662.9375,
		["class"] = "PRIEST",
		["items"] = 16,
		["resil"] = 0,
		["name"] = "歐芙珞",
		["target"] = "raid16",
		["level"] = 100,
		["time"] = 1427895845,
		["realm"] = "水晶之刺",
	},
	["Player-964-04165708"] = {
		["items"] = 15,
		["time"] = 1427894725,
		["name"] = "Aalizz",
		["score"] = 658.266666666667,
		["target"] = "raid10",
		["level"] = 100,
		["class"] = "DRUID",
		["realm"] = "冰風崗哨",
	},
	["Player-964-03E2C238"] = {
		["items"] = false,
		["name"] = "Alltimelow",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid2",
		["class"] = "PALADIN",
		["score"] = false,
		["realm"] = "",
	},
	["Player-964-03E3504C"] = {
		["items"] = false,
		["name"] = "阿啦",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid14",
		["class"] = "DRUID",
		["score"] = false,
		["realm"] = "",
	},
	["Player-964-043A5EFB"] = {
		["items"] = false,
		["name"] = "小杜",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid7",
		["class"] = "WARRIOR",
		["score"] = false,
		["realm"] = "寒冰皇冠",
	},
	["Player-964-03CF579F"] = {
		["score"] = 673.333333333333,
		["class"] = "PALADIN",
		["items"] = 15,
		["resil"] = 0,
		["time"] = 1427895780,
		["target"] = "raid18",
		["level"] = 100,
		["name"] = "乂冷乂",
		["realm"] = "冰風崗哨",
	},
	["Player-964-03E3500B"] = {
		["items"] = false,
		["name"] = "勝埼",
		["time"] = false,
		["level"] = 100,
		["target"] = "raid19",
		["class"] = "PALADIN",
		["score"] = false,
		["realm"] = "",
	},
}
