
TitanAll = {
	["TimerDualSpec"] = 2,
	["GlobalProfileUse"] = false,
	["TimerLDB"] = 2,
	["TimerAdjust"] = 1,
	["TimerVehicle"] = 1,
	["TimerPEW"] = 4,
	["GlobalProfileName"] = "<>",
}
TitanSettings = {
	["Players"] = {
		["Aalizz@冰風崗哨"] = {
			["Panel"] = {
				["FontSize"] = 12,
				["ButtonAlign"] = 1,
				["Scale"] = 1,
				["ScreenAdjust"] = false,
				["ButtonSpacing"] = 20,
				["Bar2_Transparency"] = 0.7,
				["AuxTransparency"] = 0.7,
				["TexturePath"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\X-Perl\\",
				["LockButtons"] = false,
				["BagAdjust"] = 1,
				["Buttons"] = {
					"Clock", -- [1]
					"AutoHide_Bar", -- [2]
					"Skada", -- [3]
					"SavedInstances", -- [4]
					"RaidAchievement", -- [5]
					"Location", -- [6]
					"Gold", -- [7]
					"Performance", -- [8]
					"Bag", -- [9]
					"Repair", -- [10]
				},
				["Bar_Transparency"] = 0.7,
				["FrameStrata"] = "DIALOG",
				["Bar2_Hide"] = false,
				["Transparency"] = 0.7,
				["AuxBar2_Align"] = 1,
				["Location"] = {
					"Bar", -- [1]
					"Bar", -- [2]
					"Bar", -- [3]
					"Bar", -- [4]
					"Bar", -- [5]
					"Bar", -- [6]
					"Bar", -- [7]
					"Bar", -- [8]
					"Bar", -- [9]
					"Bar", -- [10]
				},
				["TooltipFont"] = 1,
				["LockAutoHideInCombat"] = false,
				["LogAdjust"] = false,
				["Bar2_Show"] = false,
				["AuxBar_Align"] = 1,
				["TooltipTrans"] = 1,
				["Bar_Show"] = true,
				["AuxBar2_Hide"] = false,
				["VersionShown"] = 1,
				["AuxBar2_Transparency"] = 0.7,
				["AuxScreenAdjust"] = false,
				["MinimapAdjust"] = false,
				["TicketAdjust"] = 1,
				["AuxBar2_Show"] = false,
				["ToolTipsShown"] = 1,
				["IconSpacing"] = 0,
				["Position"] = 1,
				["FontName"] = "聊天",
				["Bar2_Align"] = 1,
				["HideTipsInCombat"] = false,
				["Bar_Hide"] = false,
				["Bar_Align"] = 1,
				["Silenced"] = false,
				["AuxBar_Show"] = false,
				["AuxBar_Transparency"] = 0.7,
				["AuxBar_Hide"] = false,
				["DisableTooltipFont"] = 1,
			},
			["Plugins"] = {
				["AutoHide_AuxBar2"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "AuxBar2",
				},
				["Skada"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = 1,
					["ShowLabelText"] = false,
				},
				["MoreChocolate"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = true,
				},
				["AutoHide_Bar"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "Bar",
				},
				["AutoHide_AuxBar"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "AuxBar",
				},
				["Gold"] = {
					["Initialized"] = true,
					["ShowColoredText"] = true,
					["DisplayGoldPerHour"] = true,
					["UseSeperatorComma"] = true,
					["ShowCoinLabels"] = true,
					["ShowLabelText"] = false,
					["ShowCoinIcons"] = false,
					["ShowIcon"] = true,
					["ViewAll"] = true,
					["gold"] = {
						["neg"] = false,
						["total"] = "112233",
					},
					["ShowGoldOnly"] = false,
					["ShowCoinNone"] = false,
					["SortByName"] = true,
					["UseSeperatorPeriod"] = false,
				},
				["Clock"] = {
					["HideMapTime"] = false,
					["ShowColoredText"] = false,
					["DisplayOnRightSide"] = 1,
					["OffsetHour"] = 0,
					["TimeMode"] = "Server",
					["Format"] = "12H",
					["HideGameTimeMinimap"] = false,
					["ShowLabelText"] = false,
				},
				["XP"] = {
					["UseSeperatorComma"] = true,
					["ShowSimpleRested"] = false,
					["UseSeperatorPeriod"] = false,
					["ShowLabelText"] = 1,
					["ShowSimpleNumOfKills"] = false,
					["ShowIcon"] = 1,
					["ShowSimpleNumOfGains"] = false,
					["ShowSimpleToLevel"] = false,
					["DisplayType"] = "ShowXPPerHourSession",
				},
				["SavedInstances"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = false,
				},
				["_NPCScan.Overlay"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = true,
				},
				["AutoHide_Bar2"] = {
					["DisplayOnRightSide"] = 1,
					["ForceBar"] = "Bar2",
				},
				["Prat"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = true,
				},
				["Bartender4"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = true,
				},
				["Performance"] = {
					["ShowAddonMemory"] = false,
					["ShowMemory"] = 1,
					["AddonMemoryType"] = 1,
					["ShowLatency"] = 1,
					["ShowWorldLatency"] = 1,
					["ShowLabelText"] = false,
					["ShowIcon"] = 1,
					["ShowAddonIncRate"] = false,
					["ShowColoredText"] = 1,
					["NumOfAddons"] = 5,
					["ShowFPS"] = 1,
				},
				["Decursive"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = true,
				},
				["LootType"] = {
					["RandomRoll"] = 100,
					["ShowIcon"] = 1,
					["ShowLabelText"] = 1,
					["DungeonDiffType"] = "AUTO",
					["ShowDungeonDiff"] = false,
				},
				["Volume"] = {
					["VolumeMaster"] = 1,
					["DisplayOnRightSide"] = 1,
					["VolumeDialog"] = 1,
					["VolumeInboundChat"] = 1,
					["VolumeAmbience"] = 0.600000023841858,
					["VolumeSFX"] = 1,
					["VolumeMusic"] = 0.600000023841858,
					["VolumeOutboundChat"] = 1,
					["OverrideBlizzSettings"] = false,
				},
				["Bag"] = {
					["CountProfBagSlots"] = false,
					["ShowColoredText"] = 1,
					["CountShardBagSlots"] = false,
					["ShowUsedSlots"] = 1,
					["CountAmmoPouchSlots"] = false,
					["ShowIcon"] = 1,
					["ShowDetailedInfo"] = false,
					["ShowLabelText"] = 1,
				},
				["Location"] = {
					["ShowColoredText"] = 1,
					["ShowZoneText"] = 1,
					["ShowCursorOnMap"] = true,
					["ShowLabelText"] = 1,
					["ShowLocOnMiniMap"] = 1,
					["ShowIcon"] = 1,
					["ShowCoordsOnMap"] = true,
					["CoordsFormat1"] = 1,
					["CoordsFormat2"] = false,
					["UpdateWorldmap"] = false,
					["CoordsFormat3"] = false,
				},
				["Repair"] = {
					["ShowColoredText"] = false,
					["IgnoreThrown"] = false,
					["AutoRepair"] = false,
					["DiscountFriendly"] = false,
					["ShowIcon"] = 1,
					["ShowDiscounts"] = true,
					["ShowDurabilityFrame"] = 1,
					["ShowUndamaged"] = false,
					["ShowPercentage"] = false,
					["DiscountRevered"] = false,
					["ShowInventory"] = false,
					["UseGuildBank"] = false,
					["ShowRepairCost"] = 1,
					["ShowLabelText"] = 1,
					["ShowCosts"] = true,
					["DiscountExalted"] = false,
					["ShowMostDmgPer"] = 1,
					["ShowItems"] = true,
					["AutoRepairReport"] = false,
					["DiscountHonored"] = false,
					["ShowPopup"] = false,
					["ShowMostDamaged"] = false,
				},
				["BagnonLauncher"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = true,
				},
				["RaidAchievement"] = {
					["ShowColoredText"] = false,
					["ShowIcon"] = true,
					["ShowRegularText"] = false,
					["DisplayOnRightSide"] = true,
					["ShowLabelText"] = false,
				},
			},
			["Register"] = {
				["ToBeNum"] = 21,
				["TitanPlugins"] = {
					["Repair"] = {
						["tooltipTextFunction"] = "TitanPanelRepairButton_GetTooltipText",
						["id"] = "Repair",
						["menuText"] = "裝備耐久度",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowRepairCost"] = 1,
							["AutoRepair"] = false,
							["DiscountFriendly"] = false,
							["ShowIcon"] = 1,
							["ShowDiscounts"] = true,
							["ShowDurabilityFrame"] = 1,
							["ShowUndamaged"] = false,
							["ShowPercentage"] = false,
							["DiscountRevered"] = false,
							["ShowInventory"] = false,
							["UseGuildBank"] = false,
							["IgnoreThrown"] = false,
							["ShowLabelText"] = 1,
							["ShowCosts"] = true,
							["DiscountExalted"] = false,
							["ShowMostDmgPer"] = 1,
							["ShowItems"] = true,
							["AutoRepairReport"] = false,
							["DiscountHonored"] = false,
							["ShowPopup"] = false,
							["ShowMostDamaged"] = false,
						},
						["controlVariables"] = {
							["ShowColoredText"] = true,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["iconWidth"] = 16,
						["buttonTextFunction"] = "TitanPanelRepairButton_GetButtonText",
						["icon"] = "Interface\\AddOns\\TitanRepair\\TitanRepair",
						["tooltipTitle"] = "裝備耐久度",
					},
					["Skada"] = {
						["notes"] = "",
						["iconWidth"] = 16,
						["id"] = "Skada",
						["menuText"] = "Skada",
						["category"] = "Combat",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = true,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = true,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "1.4-25",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "data source",
						["icon"] = "Interface\\Icons\\Spell_Lightning_LightningBolt01",
						["LDBVariables"] = {
							["type"] = "data source",
							["name"] = "Skada",
							["suffix"] = "",
							["value"] = "",
							["text"] = "n/a",
							["label"] = "Skada",
						},
					},
					["AutoHide_Bar"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "Bar",
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_Bar",
						["menuText"] = "AutoHide_Bar",
						["tooltipTitle"] = "自動隱藏 開/關",
					},
					["AutoHide_AuxBar"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "AuxBar",
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_AuxBar",
						["menuText"] = "AutoHide_AuxBar",
						["tooltipTitle"] = "自動隱藏 開/關",
					},
					["Gold"] = {
						["tooltipTextFunction"] = "TitanPanelGoldButton_GetTooltipText",
						["id"] = "Gold",
						["menuText"] = "金錢追蹤",
						["savedVariables"] = {
							["Initialized"] = true,
							["ShowColoredText"] = true,
							["DisplayGoldPerHour"] = true,
							["gold"] = {
								["neg"] = false,
								["total"] = "112233",
							},
							["ShowCoinLabels"] = true,
							["ShowLabelText"] = false,
							["ShowCoinIcons"] = false,
							["UseSeperatorPeriod"] = false,
							["ViewAll"] = true,
							["SortByName"] = true,
							["ShowGoldOnly"] = false,
							["ShowCoinNone"] = false,
							["UseSeperatorComma"] = true,
							["ShowIcon"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["iconWidth"] = 16,
						["buttonTextFunction"] = "TitanPanelGoldButton_FindGold",
						["icon"] = "Interface\\AddOns\\TitanGold\\Artwork\\TitanGold",
						["tooltipTitle"] = "金錢資訊",
					},
					["Performance"] = {
						["iconWidth"] = 16,
						["id"] = "Performance",
						["menuText"] = "畫面表現",
						["savedVariables"] = {
							["ShowAddonMemory"] = false,
							["ShowMemory"] = 1,
							["AddonMemoryType"] = 1,
							["ShowLatency"] = 1,
							["ShowWorldLatency"] = 1,
							["ShowLabelText"] = false,
							["ShowIcon"] = 1,
							["ShowAddonIncRate"] = false,
							["ShowColoredText"] = 1,
							["NumOfAddons"] = 5,
							["ShowFPS"] = 1,
						},
						["controlVariables"] = {
							["ShowColoredText"] = true,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["tooltipCustomFunction"] = nil --[[ skipped inline function ]],
						["icon"] = "Interface\\AddOns\\TitanPerformance\\TitanPerformance",
						["buttonTextFunction"] = "TitanPanelPerformanceButton_GetButtonText",
					},
					["XP"] = {
						["tooltipTextFunction"] = "TitanPanelXPButton_GetTooltipText",
						["id"] = "XP",
						["menuText"] = "經驗值系統(EXP)",
						["savedVariables"] = {
							["UseSeperatorComma"] = true,
							["ShowSimpleRested"] = false,
							["UseSeperatorPeriod"] = false,
							["ShowLabelText"] = 1,
							["ShowSimpleNumOfKills"] = false,
							["ShowIcon"] = 1,
							["ShowSimpleNumOfGains"] = false,
							["ShowSimpleToLevel"] = false,
							["DisplayType"] = "ShowXPPerHourSession",
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["iconWidth"] = 16,
						["buttonTextFunction"] = "TitanPanelXPButton_GetButtonText",
						["tooltipTitle"] = "EXP 經驗值資訊",
					},
					["SavedInstances"] = {
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["iconWidth"] = 16,
						["id"] = "SavedInstances",
						["menuText"] = "SavedInstances",
						["category"] = "Information",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "6.0.0",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Addons\\SavedInstances\\icon.tga",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "SavedInstances",
							["suffix"] = "",
							["value"] = "",
							["text"] = "SavedInstances",
							["label"] = "SavedInstances",
						},
					},
					["_NPCScan.Overlay"] = {
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["iconWidth"] = 16,
						["id"] = "_NPCScan.Overlay",
						["menuText"] = "_NPCScan.Overlay",
						["category"] = "Interface",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "6.0.2.1",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Icons\\INV_Misc_EngGizmos_20",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "_NPCScan.Overlay",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "_NPCScan.Overlay",
						},
					},
					["AutoHide_Bar2"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "Bar2",
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_Bar2",
						["menuText"] = "AutoHide_Bar2",
						["tooltipTitle"] = "自動隱藏 開/關",
					},
					["Clock"] = {
						["tooltipTextFunction"] = "TitanPanelClockButton_GetTooltipText",
						["id"] = "Clock",
						["menuText"] = "時鐘",
						["savedVariables"] = {
							["OffsetHour"] = 0,
							["ShowColoredText"] = false,
							["DisplayOnRightSide"] = 1,
							["HideMapTime"] = false,
							["HideGameTimeMinimap"] = false,
							["Format"] = "12H",
							["TimeMode"] = "Server",
							["ShowLabelText"] = false,
						},
						["controlVariables"] = {
							["ShowColoredText"] = true,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["buttonTextFunction"] = "TitanPanelClockButton_GetButtonText",
						["tooltipTitle"] = "時鐘",
					},
					["Bartender4"] = {
						["notes"] = "",
						["iconWidth"] = 16,
						["id"] = "Bartender4",
						["menuText"] = "Bartender4",
						["category"] = "Interface",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "4.6.3",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Icons\\INV_Drink_05",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "Bartender4",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "Bartender4",
						},
					},
					["LootType"] = {
						["tooltipTextFunction"] = "TitanPanelLootTypeButton_GetTooltipText",
						["id"] = "LootType",
						["menuText"] = "拾取方式",
						["savedVariables"] = {
							["RandomRoll"] = 100,
							["ShowIcon"] = 1,
							["DungeonDiffType"] = "AUTO",
							["ShowDungeonDiff"] = false,
							["ShowLabelText"] = 1,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["iconWidth"] = 16,
						["buttonTextFunction"] = "TitanPanelLootTypeButton_GetButtonText",
						["icon"] = "Interface\\AddOns\\TitanLootType\\TitanLootType",
						["tooltipTitle"] = "拾取方式",
					},
					["Decursive"] = {
						["notes"] = "",
						["iconWidth"] = 16,
						["id"] = "Decursive",
						["menuText"] = "Decursive",
						["category"] = "Combat",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["version"] = "2.7.3.6",
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\AddOns\\Decursive\\iconON.tga",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "Decursive",
							["suffix"] = "",
							["value"] = "",
							["text"] = "Decursive",
							["label"] = "Decursive",
						},
					},
					["Prat"] = {
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["iconWidth"] = 16,
						["id"] = "Prat",
						["menuText"] = "Prat",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Addons\\Prat-3.0\\textures\\chat-bubble",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "Prat",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "Prat |cff8080ff3.0|r",
						},
					},
					["AutoHide_AuxBar2"] = {
						["savedVariables"] = {
							["DisplayOnRightSide"] = 1,
							["ForceBar"] = "AuxBar2",
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["id"] = "AutoHide_AuxBar2",
						["menuText"] = "AutoHide_AuxBar2",
						["tooltipTitle"] = "自動隱藏 開/關",
					},
					["Bag"] = {
						["tooltipTextFunction"] = "TitanPanelBagButton_GetTooltipText",
						["id"] = "Bag",
						["menuText"] = "背包",
						["savedVariables"] = {
							["ShowColoredText"] = 1,
							["CountProfBagSlots"] = false,
							["CountShardBagSlots"] = false,
							["ShowUsedSlots"] = 1,
							["CountAmmoPouchSlots"] = false,
							["ShowIcon"] = 1,
							["ShowDetailedInfo"] = false,
							["ShowLabelText"] = 1,
						},
						["controlVariables"] = {
							["ShowColoredText"] = true,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["iconWidth"] = 16,
						["buttonTextFunction"] = "TitanPanelBagButton_GetButtonText",
						["icon"] = "Interface\\AddOns\\TitanBag\\TitanBag",
						["tooltipTitle"] = "背包",
					},
					["Location"] = {
						["tooltipTextFunction"] = "TitanPanelLocationButton_GetTooltipText",
						["id"] = "Location",
						["menuText"] = "位置",
						["savedVariables"] = {
							["ShowColoredText"] = 1,
							["ShowZoneText"] = 1,
							["ShowCursorOnMap"] = true,
							["ShowLabelText"] = 1,
							["UpdateWorldmap"] = false,
							["ShowIcon"] = 1,
							["CoordsFormat3"] = false,
							["CoordsFormat1"] = 1,
							["CoordsFormat2"] = false,
							["ShowCoordsOnMap"] = true,
							["ShowLocOnMiniMap"] = 1,
						},
						["controlVariables"] = {
							["ShowColoredText"] = true,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = false,
							["ShowLabelText"] = true,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["iconWidth"] = 16,
						["buttonTextFunction"] = "TitanPanelLocationButton_GetButtonText",
						["icon"] = "Interface\\AddOns\\TitanLocation\\TitanLocation",
						["tooltipTitle"] = "座標資訊",
					},
					["Volume"] = {
						["tooltipTextFunction"] = "TitanPanelVolumeButton_GetTooltipText",
						["id"] = "Volume",
						["menuText"] = "音量",
						["savedVariables"] = {
							["VolumeMaster"] = 1,
							["DisplayOnRightSide"] = 1,
							["VolumeDialog"] = 0.5,
							["OverrideBlizzSettings"] = false,
							["VolumeAmbience"] = 0.5,
							["VolumeSFX"] = 0.5,
							["VolumeInboundChat"] = 1,
							["VolumeOutboundChat"] = 1,
							["VolumeMusic"] = 0.5,
						},
						["version"] = "5.4.3.60000",
						["category"] = "Built-ins",
						["iconButtonWidth"] = 18,
						["iconWidth"] = 32,
						["tooltipTitle"] = "音量控制",
					},
					["BagnonLauncher"] = {
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["iconWidth"] = 16,
						["id"] = "BagnonLauncher",
						["menuText"] = "BagnonLauncher",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "Interface\\Icons\\INV_Misc_Bag_07",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "BagnonLauncher",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "Bagnon",
						},
					},
					["RaidAchievement"] = {
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["iconWidth"] = 16,
						["id"] = "RaidAchievement",
						["menuText"] = "RaidAchievement",
						["savedVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = true,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["controlVariables"] = {
							["ShowColoredText"] = false,
							["ShowIcon"] = false,
							["ShowRegularText"] = false,
							["DisplayOnRightSide"] = true,
							["ShowLabelText"] = true,
						},
						["buttonTextFunction"] = "TitanLDBShowText",
						["ldb"] = "launcher",
						["icon"] = "interface\\AddOns\\RaidAchievement\\ra_button_e",
						["LDBVariables"] = {
							["type"] = "launcher",
							["name"] = "RaidAchievement",
							["suffix"] = "",
							["value"] = "",
							["text"] = "",
							["label"] = "RA",
						},
					},
				},
				["ToBe"] = {
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "Bar",
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_Bar",
								["menuText"] = "AutoHide_Bar",
								["tooltipTitle"] = "自動隱藏 開/關",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_Bar",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_BarButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [1]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "Bar2",
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_Bar2",
								["menuText"] = "AutoHide_Bar2",
								["tooltipTitle"] = "自動隱藏 開/關",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_Bar2",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_Bar2Button",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [2]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "AuxBar2",
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_AuxBar2",
								["menuText"] = "AutoHide_AuxBar2",
								["tooltipTitle"] = "自動隱藏 開/關",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_AuxBar2",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_AuxBar2Button",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [3]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["savedVariables"] = {
									["DisplayOnRightSide"] = 1,
									["ForceBar"] = "AuxBar",
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["id"] = "AutoHide_AuxBar",
								["menuText"] = "AutoHide_AuxBar",
								["tooltipTitle"] = "自動隱藏 開/關",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "AutoHide_AuxBar",
						["category"] = "Built-ins",
						["button"] = "TitanPanelAutoHide_AuxBarButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [4]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelBagButton_GetTooltipText",
								["id"] = "Bag",
								["menuText"] = "背包",
								["savedVariables"] = {
									["ShowColoredText"] = 1,
									["CountProfBagSlots"] = false,
									["CountShardBagSlots"] = false,
									["ShowUsedSlots"] = 1,
									["CountAmmoPouchSlots"] = false,
									["ShowIcon"] = 1,
									["ShowDetailedInfo"] = false,
									["ShowLabelText"] = 1,
								},
								["controlVariables"] = {
									["ShowColoredText"] = true,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["iconWidth"] = 16,
								["buttonTextFunction"] = "TitanPanelBagButton_GetButtonText",
								["icon"] = "Interface\\AddOns\\TitanBag\\TitanBag",
								["tooltipTitle"] = "背包",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Bag",
						["category"] = "Built-ins",
						["button"] = "TitanPanelBagButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [5]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelClockButton_GetTooltipText",
								["id"] = "Clock",
								["menuText"] = "時鐘",
								["savedVariables"] = {
									["OffsetHour"] = 0,
									["ShowColoredText"] = false,
									["DisplayOnRightSide"] = 1,
									["HideMapTime"] = false,
									["HideGameTimeMinimap"] = false,
									["Format"] = "12H",
									["TimeMode"] = "Server",
									["ShowLabelText"] = false,
								},
								["controlVariables"] = {
									["ShowColoredText"] = true,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["buttonTextFunction"] = "TitanPanelClockButton_GetButtonText",
								["tooltipTitle"] = "時鐘",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Clock",
						["category"] = "Built-ins",
						["button"] = "TitanPanelClockButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [6]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelGoldButton_GetTooltipText",
								["id"] = "Gold",
								["menuText"] = "金錢追蹤",
								["savedVariables"] = {
									["Initialized"] = true,
									["ShowColoredText"] = true,
									["DisplayGoldPerHour"] = true,
									["gold"] = {
										["neg"] = false,
										["total"] = "112233",
									},
									["ShowCoinLabels"] = true,
									["ShowLabelText"] = false,
									["ShowCoinIcons"] = false,
									["UseSeperatorPeriod"] = false,
									["ViewAll"] = true,
									["SortByName"] = true,
									["ShowGoldOnly"] = false,
									["ShowCoinNone"] = false,
									["UseSeperatorComma"] = true,
									["ShowIcon"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["iconWidth"] = 16,
								["buttonTextFunction"] = "TitanPanelGoldButton_FindGold",
								["icon"] = "Interface\\AddOns\\TitanGold\\Artwork\\TitanGold",
								["tooltipTitle"] = "金錢資訊",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Gold",
						["category"] = "Built-ins",
						["button"] = "TitanPanelGoldButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [7]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelLocationButton_GetTooltipText",
								["id"] = "Location",
								["menuText"] = "位置",
								["savedVariables"] = {
									["ShowColoredText"] = 1,
									["ShowZoneText"] = 1,
									["ShowCursorOnMap"] = true,
									["ShowLabelText"] = 1,
									["UpdateWorldmap"] = false,
									["ShowIcon"] = 1,
									["CoordsFormat3"] = false,
									["CoordsFormat1"] = 1,
									["CoordsFormat2"] = false,
									["ShowCoordsOnMap"] = true,
									["ShowLocOnMiniMap"] = 1,
								},
								["controlVariables"] = {
									["ShowColoredText"] = true,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["iconWidth"] = 16,
								["buttonTextFunction"] = "TitanPanelLocationButton_GetButtonText",
								["icon"] = "Interface\\AddOns\\TitanLocation\\TitanLocation",
								["tooltipTitle"] = "座標資訊",
							},
							["subZoneText"] = "",
							["factionName"] = "",
							["px"] = 0.397027969360352,
							["py"] = 0.534295797348022,
							["pvpType"] = "contested",
							["zoneText"] = "市政廳",
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Location",
						["category"] = "Built-ins",
						["button"] = "TitanPanelLocationButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [8]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelLootTypeButton_GetTooltipText",
								["id"] = "LootType",
								["menuText"] = "拾取方式",
								["savedVariables"] = {
									["RandomRoll"] = 100,
									["ShowIcon"] = 1,
									["DungeonDiffType"] = "AUTO",
									["ShowDungeonDiff"] = false,
									["ShowLabelText"] = 1,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["iconWidth"] = 16,
								["buttonTextFunction"] = "TitanPanelLootTypeButton_GetButtonText",
								["icon"] = "Interface\\AddOns\\TitanLootType\\TitanLootType",
								["tooltipTitle"] = "拾取方式",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "LootType",
						["category"] = "Built-ins",
						["button"] = "TitanPanelLootTypeButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [9]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["iconWidth"] = 16,
								["id"] = "Performance",
								["menuText"] = "畫面表現",
								["savedVariables"] = {
									["ShowAddonMemory"] = false,
									["ShowMemory"] = 1,
									["AddonMemoryType"] = 1,
									["ShowLatency"] = 1,
									["ShowWorldLatency"] = 1,
									["ShowLabelText"] = false,
									["ShowIcon"] = 1,
									["ShowAddonIncRate"] = false,
									["ShowColoredText"] = 1,
									["NumOfAddons"] = 5,
									["ShowFPS"] = 1,
								},
								["controlVariables"] = {
									["ShowColoredText"] = true,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["tooltipCustomFunction"] = nil --[[ skipped inline function ]],
								["icon"] = "Interface\\AddOns\\TitanPerformance\\TitanPerformance",
								["buttonTextFunction"] = "TitanPanelPerformanceButton_GetButtonText",
							},
							["maxFPS"] = 1000,
							["minFPS"] = 10.4785175323486,
							["initialMemory"] = 61702,
							["startSessionTime"] = 1422675964,
							["fps"] = 99.3377380371094,
							["memory"] = 67553,
							["bandwidthIn"] = 0.992468893527985,
							["fpsSampleCount"] = 2020,
							["avgFPS"] = 58.101534319396,
							["latencyHome"] = 154,
							["bandwidthOut"] = 0.34902423620224,
							["latencyWorld"] = 76,
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Performance",
						["category"] = "Built-ins",
						["button"] = "TitanPanelPerformanceButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [10]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelRepairButton_GetTooltipText",
								["id"] = "Repair",
								["menuText"] = "裝備耐久度",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowRepairCost"] = 1,
									["AutoRepair"] = false,
									["DiscountFriendly"] = false,
									["ShowIcon"] = 1,
									["ShowDiscounts"] = true,
									["ShowDurabilityFrame"] = 1,
									["ShowUndamaged"] = false,
									["ShowPercentage"] = false,
									["DiscountRevered"] = false,
									["ShowInventory"] = false,
									["UseGuildBank"] = false,
									["IgnoreThrown"] = false,
									["ShowLabelText"] = 1,
									["ShowCosts"] = true,
									["DiscountExalted"] = false,
									["ShowMostDmgPer"] = 1,
									["ShowItems"] = true,
									["AutoRepairReport"] = false,
									["DiscountHonored"] = false,
									["ShowPopup"] = false,
									["ShowMostDamaged"] = false,
								},
								["controlVariables"] = {
									["ShowColoredText"] = true,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["iconWidth"] = 16,
								["buttonTextFunction"] = "TitanPanelRepairButton_GetButtonText",
								["icon"] = "Interface\\AddOns\\TitanRepair\\TitanRepair",
								["tooltipTitle"] = "裝備耐久度",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Repair",
						["category"] = "Built-ins",
						["button"] = "TitanPanelRepairButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [11]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelVolumeButton_GetTooltipText",
								["id"] = "Volume",
								["menuText"] = "音量",
								["savedVariables"] = {
									["VolumeMaster"] = 1,
									["DisplayOnRightSide"] = 1,
									["VolumeDialog"] = 0.5,
									["OverrideBlizzSettings"] = false,
									["VolumeAmbience"] = 0.5,
									["VolumeSFX"] = 0.5,
									["VolumeInboundChat"] = 1,
									["VolumeOutboundChat"] = 1,
									["VolumeMusic"] = 0.5,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["iconButtonWidth"] = 18,
								["iconWidth"] = 32,
								["tooltipTitle"] = "音量控制",
							},
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "Volume",
						["category"] = "Built-ins",
						["button"] = "TitanPanelVolumeButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [12]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["tooltipTextFunction"] = "TitanPanelXPButton_GetTooltipText",
								["id"] = "XP",
								["menuText"] = "經驗值系統(EXP)",
								["savedVariables"] = {
									["UseSeperatorComma"] = true,
									["ShowSimpleRested"] = false,
									["UseSeperatorPeriod"] = false,
									["ShowLabelText"] = 1,
									["ShowSimpleNumOfKills"] = false,
									["ShowIcon"] = 1,
									["ShowSimpleNumOfGains"] = false,
									["ShowSimpleToLevel"] = false,
									["DisplayType"] = "ShowXPPerHourSession",
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["version"] = "5.4.3.60000",
								["category"] = "Built-ins",
								["iconWidth"] = 16,
								["buttonTextFunction"] = "TitanPanelXPButton_GetButtonText",
								["tooltipTitle"] = "EXP 經驗值資訊",
							},
							["totalTime"] = 3415526,
							["initXP"] = 878,
							["startSessionTime"] = 1422672995,
							["accumXP"] = 0,
							["levelTime"] = 44505,
							["sessionTime"] = 1422672995,
							["sessionXP"] = 0,
						},
						["notes"] = "",
						["plugin_type"] = "Titan",
						["name"] = "XP",
						["category"] = "Built-ins",
						["button"] = "TitanPanelXPButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [13]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "",
								["iconWidth"] = 16,
								["id"] = "Decursive",
								["menuText"] = "Decursive",
								["category"] = "Combat",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "2.7.3.6",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\AddOns\\Decursive\\iconON.tga",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "Decursive",
									["suffix"] = "",
									["value"] = "",
									["text"] = "Decursive",
									["label"] = "Decursive",
								},
							},
						},
						["notes"] = "",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "Decursive",
						["category"] = "Combat",
						["button"] = "TitanPanelDecursiveButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [14]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "",
								["iconWidth"] = 16,
								["id"] = "Skada",
								["menuText"] = "Skada",
								["category"] = "Combat",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = true,
									["DisplayOnRightSide"] = false,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = true,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "1.4-25",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "data source",
								["icon"] = "Interface\\Icons\\Spell_Lightning_LightningBolt01",
								["LDBVariables"] = {
									["type"] = "data source",
									["name"] = "Skada",
									["suffix"] = "",
									["value"] = "",
									["text"] = "n/a",
									["label"] = "Skada",
								},
							},
						},
						["notes"] = "",
						["plugin_type"] = "LDB: 'data source'",
						["name"] = "Skada",
						["category"] = "Combat",
						["button"] = "TitanPanelSkadaButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [15]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
								["iconWidth"] = 16,
								["id"] = "_NPCScan.Overlay",
								["menuText"] = "_NPCScan.Overlay",
								["category"] = "Interface",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "6.0.2.1",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Icons\\INV_Misc_EngGizmos_20",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "_NPCScan.Overlay",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "_NPCScan.Overlay",
								},
							},
						},
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "_NPCScan.Overlay",
						["category"] = "Interface",
						["button"] = "TitanPanel_NPCScan.OverlayButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [16]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
								["iconWidth"] = 16,
								["id"] = "Prat",
								["menuText"] = "Prat",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Addons\\Prat-3.0\\textures\\chat-bubble",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "Prat",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "Prat |cff8080ff3.0|r",
								},
							},
						},
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "Prat",
						["category"] = "General",
						["button"] = "TitanPanelPratButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [17]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
								["iconWidth"] = 16,
								["id"] = "BagnonLauncher",
								["menuText"] = "BagnonLauncher",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Icons\\INV_Misc_Bag_07",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "BagnonLauncher",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "Bagnon",
								},
							},
						},
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "BagnonLauncher",
						["category"] = "General",
						["button"] = "TitanPanelBagnonLauncherButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [18]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
								["iconWidth"] = 16,
								["id"] = "SavedInstances",
								["menuText"] = "SavedInstances",
								["category"] = "Information",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "6.0.0",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Addons\\SavedInstances\\icon.tga",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "SavedInstances",
									["suffix"] = "",
									["value"] = "",
									["text"] = "SavedInstances",
									["label"] = "SavedInstances",
								},
							},
						},
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "SavedInstances",
						["category"] = "Information",
						["button"] = "TitanPanelSavedInstancesButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [19]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "",
								["iconWidth"] = 16,
								["id"] = "Bartender4",
								["menuText"] = "Bartender4",
								["category"] = "Interface",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["version"] = "4.6.3",
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "Interface\\Icons\\INV_Drink_05",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "Bartender4",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "Bartender4",
								},
							},
						},
						["notes"] = "",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "Bartender4",
						["category"] = "Interface",
						["button"] = "TitanPanelBartender4Button",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [20]
					{
						["self"] = {
							[0] = nil --[[ skipped userdata ]],
							["registry"] = {
								["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
								["iconWidth"] = 16,
								["id"] = "RaidAchievement",
								["menuText"] = "RaidAchievement",
								["savedVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = true,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["controlVariables"] = {
									["ShowColoredText"] = false,
									["ShowIcon"] = false,
									["ShowRegularText"] = false,
									["DisplayOnRightSide"] = true,
									["ShowLabelText"] = true,
								},
								["buttonTextFunction"] = "TitanLDBShowText",
								["ldb"] = "launcher",
								["icon"] = "interface\\AddOns\\RaidAchievement\\ra_button_e",
								["LDBVariables"] = {
									["type"] = "launcher",
									["name"] = "RaidAchievement",
									["suffix"] = "",
									["value"] = "",
									["text"] = "",
									["label"] = "RA",
								},
							},
						},
						["notes"] = "\nThis is a LDB 'launcher' without .label using .text instead!!!!",
						["plugin_type"] = "LDB: 'launcher'",
						["name"] = "RaidAchievement",
						["category"] = "General",
						["button"] = "TitanPanelRaidAchievementButton",
						["issue"] = "",
						["isChild"] = false,
						["status"] = "|cff20ff20Registered|r",
					}, -- [21]
				},
				["Extras"] = {
					{
						["id"] = "MoreChocolate",
						["num"] = 1,
					}, -- [1]
				},
			},
		},
	},
	["Player"] = "Aalizz@冰風崗哨",
	["Version"] = "5.4.3.60000",
	["Profile"] = "Aalizz@冰風崗哨",
}
TitanSkins = {
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\",
		["name"] = "Titan Default",
	}, -- [1]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\BlackPlusOne Skin\\",
		["name"] = "BlackPlusOne",
	}, -- [2]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Christmas Skin\\",
		["name"] = "Christmas",
	}, -- [3]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Charcoal Metal\\",
		["name"] = "Charcoal Metal",
	}, -- [4]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Crusader Skin\\",
		["name"] = "Crusader",
	}, -- [5]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Cursed Orange Skin\\",
		["name"] = "Cursed Orange",
	}, -- [6]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Dark Wood Skin\\",
		["name"] = "Dark Wood",
	}, -- [7]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Deep Cave Skin\\",
		["name"] = "Deep Cave",
	}, -- [8]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Elfwood Skin\\",
		["name"] = "Elfwood",
	}, -- [9]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Engineer Skin\\",
		["name"] = "Engineer",
	}, -- [10]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Frozen Metal Skin\\",
		["name"] = "Frozen Metal",
	}, -- [11]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Graphic Skin\\",
		["name"] = "Graphic",
	}, -- [12]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Graveyard Skin\\",
		["name"] = "Graveyard",
	}, -- [13]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Hidden Leaf Skin\\",
		["name"] = "Hidden Leaf",
	}, -- [14]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Holy Warrior Skin\\",
		["name"] = "Holy Warrior",
	}, -- [15]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Nightlife Skin\\",
		["name"] = "Nightlife",
	}, -- [16]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Orgrimmar Skin\\",
		["name"] = "Orgrimmar",
	}, -- [17]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Plate Skin\\",
		["name"] = "Plate",
	}, -- [18]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\Tribal Skin\\",
		["name"] = "Tribal",
	}, -- [19]
	{
		["titan"] = true,
		["path"] = "Interface\\AddOns\\Titan\\Artwork\\Custom\\X-Perl\\",
		["name"] = "X-Perl",
	}, -- [20]
}
ServerTimeOffsets = {
}
ServerHourFormat = {
}
